.github/workflows/ci.yml

Add Compatibility Check Workflow

---

Dockerfile

Update Grafana 9.1.6 dockerfile

---

CHANGELOG.md
Dockerfile
package.json
yarn.lock

1. Update to the latest version of Grafana.
2. Fix customization.

Update to Grafana 9.2.2

---

.github/workflows/ci.yml
.github/workflows/docker.yml
.github/workflows/release.yml
CHANGELOG.md

Update to the last GitHub Actions

Update CI to Node 16 and Synchronize with Release workflow

---

CHANGELOG.md
README.md
package.json
provisioning/dashboards/news.json
provisioning/datasources/datasource.yaml

1. Update URL and content for new Blog based on Docusaurus.
2. README updates.

Update URL and content for new Blog based on Docusaurus

---

CHANGELOG.md
Dockerfile
package.json
yarn.lock

Keep up to date with the latest version of Grafana.

Update to Grafana 9.3.6

---

Dockerfile
README.md
package.json
provisioning/dashboards/news.json
yarn.lock

1. Keep up to date with the latest version of Grafana toolkit.
2. Resolves #43.

Upgrade to Grafana 9.3.6

---

CHANGELOG.md
Dockerfile

Update Docker customization to Grafana 9.4.2

---

CHANGELOG.md
Dockerfile

By @jacksongoode
```
Hi, I just wanted to highlight that when we made this switch we found the minified variables in the match had changed and opted to rewrote some of these replaces with more robust regex searches that will hopefully survive over version changes:
RUN find /usr/share/grafana/public/build/ -name *.js -exec \
sed -i 's|AppTitle="Grafana")|AppTitle="App")|g; \
s|Welcome to Grafana|Welcome to App|g; \
s|\[{target:"_blank",id:"documentation".*grafana_footer"}\]|\[\]|g; \
s|({target:"_blank",id:"version",.*licenseUrl})|()|g; \
s|({target:"_blank",id:"version",.*CHANGELOG.md":void 0})|()|g; \
s|({target:"_blank",id:"updateVersion",.*grafana_footer"})|()|g' \
{} \;
Hopefully this can be useful!
```
Thank you.

Update JS updates in Dockerfile

---

CHANGELOG.md
Dockerfile

Unused panels in our projects.

Remove Native Panels

---

Dockerfile

Customize Grafana Title

---

.github/workflows/docker.yml
CHANGELOG.md
README.md
package.json
yarn.lock

Keep up to date with the latest Grafana toolkit.

Update to Grafana 9.5.1

---

CHANGELOG.md
Dockerfile

1. Remove Connections.
2. Update Licenses.
3. Update to 9.5.1.

Update Docker image 9.5.1

---

CHANGELOG.md
Dockerfile
README.md
package.json
yarn.lock

Keep up to date with the latest Grafana version.

Update to Grafana 9.5.2

---

jest-setup.js
package.json
src/components/Config/Config.test.tsx
src/components/Config/Config.tsx
src/components/RootPage/RootPage.test.tsx
src/components/RootPage/RootPage.tsx
src/constants.ts
src/constants/app.ts
src/constants/index.ts
src/constants/tests.ts
yarn.lock

Update from Enzyme to testing-library/react.

Rewrite unit tests with testing-library/react

---

README.md
src/plugin.json

Add YouTube to support

---

Dockerfile

Remove News icon

---

CHANGELOG.md
Dockerfile
src/components/Plugins/Variable.tsx

Update to Grafana 10.0.2

---

Dockerfile

https://github.com/VolkovLabs/volkovlabs.io/issues/472

Move Application plugin to Root

---

.config/.eslintrc
.config/.prettierrc.js
.config/webpack/utils.ts
.config/webpack/webpack.config.ts
.eslintrc
CHANGELOG.md
package-lock.json
package.json
src/components/App/App.test.tsx
src/components/App/App.tsx
src/components/Community/Community.tsx
src/components/Config/Config.test.tsx
src/components/Config/Config.tsx
src/components/Development/Development.tsx
src/components/Plugins/ApacheECharts.tsx
src/components/Plugins/Balena.tsx
src/components/Plugins/Base64Image.tsx
src/components/Plugins/Calendar.tsx
src/components/Plugins/DataManipulation.tsx
src/components/Plugins/DynamicText.tsx
src/components/Plugins/Environment.tsx
src/components/Plugins/GrafanaAPI.tsx
src/components/Plugins/RSSAtom.tsx
src/components/Plugins/Static.tsx
src/components/Plugins/Variable.tsx
src/constants/app.ts
src/constants/tests.ts
src/module.test.ts
src/module.ts
src/types.ts

1. Update to Plugin Tools.
2. Using the latest `@volkovlabs/eslint-config` package.

Update ESLint configuration and refactoring
